apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: innovation-postgres-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: cephfs
